### PR TITLE
PAN-2075: Change permissions

### PR DESCRIPTION
**Pull request by jacekv**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [X] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
The report from SonartCloud is not reported in the PR comment section - changing the permissions fixes the problem. To see the result, go here: https://github.com/pantos-io/servicenode/pull/49
## Related Tickets & Documents

- Related Issue #
- Closes #

## QA Instructions

_Please replace this line with instructions on how to test your changes._

### CODE REVIEW

**Comment by jacekv** [comment]
@jpantos Why have those permissions been set to `read` and not `write`? Is there a reason for that? Any security concerns?

**Comment by juanmanuel-tirado** [comment]
If I remember correctly the security hardener recommended `read` instead of write, but probably it could not detect the operation from Sonar.

**Comment by juanmanuel-tirado** [comment]
Happy to approve and merge when ready to be PR.

**Comment by jpantos** [comment]
Yeah I think that what Juan says is entirely true. If I'm not wrong, sonar uses the token asynchronously so the hardener will claim it needs to be read. May be worth to add a comment there for the future.

**Comment by jacekv** [comment]
Alright

**Comment by jacekv** [comment]
Ready to be reviewed

**Review by jpantos — APPROVED** [review]

**Review by juanmanuel-tirado — APPROVED** [review]
A new version has to be released after merged.

**Comment by jacekv** [comment]
@juanmanuel-tirado A new version has been released

**Pull request merged**
